


import Image from "next/image"
 import styles from "../Styles/Pages.module.css"

   export default function Study(){
      return(
          <>
          <div className="Study_section container">
            <div className={styles.container}>
              <div className={styles.row}>
                <div className={styles.col_md_7}>
                  <div className={styles.text_material}>
                 
                  <h3 className={styles.text_start}>
                  Thyroid Hormone Study
                  </h3>
                  <p className={styles.fw_bold}>
                  Principle Investigator: <span className={styles.fw_lighter}> Ralf Paus</span>
                  </p>
                  <p className={styles.fw_bold}>
                  Partners: <span className={styles.fw_lighter}>Cutaneon & University of Miami</span>
                  </p>
                  <div className={styles.img_responsive}>
                  <a className={styles.text_field } href="/">
                    <Image className={styles.img_fluid} width="500" height="500" src="/Studycardimg4.png" alt="Logo1" />
                  </a>
                  <a className="navbar-brand text-white" href="/">
                 <Image className={styles.img_fluid} width="335" height="256" src="/Studyimage4.png" alt="Logo1" />
               </a>
                  </div>
                  <p className={styles.fw_bold}>
                About: <span className={styles.fw_lighter}>Based on prior research by Professor Ralf Paus, HairDAO funded an in vitro experiment, testing the hair growth effects of synthetic T3 and T4 thyroid hormones on human scalp skin. Both T3 and T4 have well documented pharmacokinetics based on their oral use at much higher dosages to treat hypothyroidism.<br/> <br/>
             
             Data from our in vitro research has led to an in vivo observational study being conducted under the supervision of Dr. Blake Bloxham in Florida. If you’re interested in participating in the study,
             <a className="text-link" href="/#">
             Apply Here.</a></span>
               </p>
                  <h3 className={styles.fw_bold}>
                Timeline:18 Months</h3>
                <h3 className={styles.fw_bold}>
                  6 Months: <span className={styles.fw_lighter}> Completed</span>
                  </h3>
                  <div className={styles.fw_lighter}>
                <ul className="">
                  <li>
                    <p>Establish two different, clinically applicable topical T3/T4 vehicles </p>
                    </li>
                    <li><p>Combination therapies, dosage, and protocol improvements will be generated by HairDAO in collaboration with Dr. Barghouthi and Dr. Bloxham.</p>
                    </li>
                    <li><p>Provide immunostaining pilot data using one human scalp skin biopsy, testing multiple dosages of T3/T4 using both vehicles </p>

                    </li>
                  </ul> 
                    </div>
                <p className={styles.fw_bold} >
                  12 Months: <span className={styles.fw_lighter}> Completed</span>
                  </p>
                  <div className={styles.fw_lighter}>
                <ul>
                  <li><p>Confirm initial pilot data using both vehicles, testing T3 and T4 individually as well as in combination at different dosages.</p>
                    </li>
                    <li><p>Assess all read-out parameters using three scalp skin biopsies. </p>
                    </li>
                    </ul>
                    
                <h3 className="text-start mt-4 text-black fw-bold" >
                  18 Months: <span className={styles.fw_lighter}> Ongoing</span>
                  </h3>
                  <div className="mt-4">
                <ul>
                  <li>
                <p>Test our optimized formulation on patients under the supervision of Dr. Blake Bloxham. 
                </p>
                </li>
                  
                  </ul>
                    </div>
                    </div>
                  
                    </div>
                </div>
                <div className={`${styles.col_md_4} ${styles.imgcol}`}>
              <div className={styles.mobile_img}>
                  <a  href="/">
                    <Image className={styles.img_fluid} width="335" height="256" src="/Studycardimg4.png" alt="Logo1" />
                  </a>
                  <a className="navbar-brand text-white" href="/">
                 <Image className={styles.img_fluid} width="335" height="256" src="/Studyimage4.png" alt="Logo1" />
               </a>
               </div>
                  <div className={styles.img_text}>
                <h3 className={styles.text_center} >
                Dutasteride IP
                  </h3>
                  <div className={styles.text_left}>
                  <p className={styles.fw_bold}>Funding:
                 <span className={styles.fw_lighter}>$125,000.00</span>
                  </p>
                  <p className={styles.fw_bold}>Initiated:
                 <span className={styles.fw_lighter}>11/16/22</span>
                  </p>
                  <p className={styles.fw_bold}>Ownership:
                 <span className={styles.fw_lighter}> 95%</span>
                  </p>
                  <p className={styles.fw_bold}>Patent Status
                 <span className={styles.fw_lighter}>Filed</span>
                 
                  </p>
                    </div>
                  </div>
                </div>
            </div>
            </div>
            </div>
         </>
      )
  }





