import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-icons/font/bootstrap-icons.css'
import './globals.css'
import { Inter } from 'next/font/google'
import BootstrapClient from '@/components/BootstrapClient.js';
import Header from './Header/page';
import Footer from './Footer/page';
import { Roboto_Condensed } from 'next/font/google'

const roboto = Roboto_Condensed({ 
  weight: ['300', '400', '700'],
  subsets: ['greek'],
  display: 'swap' 
})

// const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="Favicon.png" type="image/png" sizes="20" />
      </head>
      <body className={roboto.className}>
        <Header/>
        
        {children}
   
        
        <Footer/>
    
        <BootstrapClient/>
    
       
      </body>
    </html>
  )
}
