  import Image from "next/image"
  export default function Study(){
      return(
          <>
          <main>
            <div className="Study_section container   mt-5">
              <div className="container">
              <div className="row ">
                <div className="col-lg-8 col-12 me-5 ">
                  <h3 className="text-start  fw-bold">
                  YAP-1 Inhibition Study
                  </h3>
                  <h5 className="text-start mt-4 text-black fw-bold" >
                  Principle Investigator: <span className="fw-lighter"> Dr.Taleb Barghouthi, Dr. Blake Bloxham</span>
                  </h5>
                  <h5 className="text-start mt-4 text-black fw-bold" >
                About: <span className="fw-lighter">YAP-1 downregulation offers a path to reduced scarring in hair transplants, allowing for potential neogenesis of hair follicles in the donor region from which follicles are extracted in transplants. Reduced scarring, even if only mildly obtained, has profound benefits for hair transplant patients. Significantly reduced scarring, if allowing for hair regrowth at the scar site, would not only significantly reduce the risks of hair transplants, but also offer a path to follow-on hair transplants utilizing the same follicle sites extracted in past transplants <br/> <br/>
                
                HairDAO, in collaboration Dr. Taleb Barghouthi and Dr. Blake Bloxham, has purchased the most innovative tricholab equipment on market today, allowing for best-in-class measurements of hair and skin performance without the need for tatooing the patient's scalp. The equipment HairDAO has purchased will allow Dr. Barghouthi and Bloxham to better analyze the patients on which they administer FDA-approved, off-label Verteporfin, the most prominent YAP-1 inhibitor on the market today. Alongise, Dr. Barghouthi and Dr. Bloxham, HairDAO will continue develop better YAP-1 inhibition strategies, though combination therapies and improved dosage and protocol testing. Paths to monetization include developing, patenting and protocolizing novel YAP-1 inhibition strategies.</span>
                  </h5>
                  
                  <h5 className="text-start mt-4 text-black fw-bold" >
                Timeline: 12 Months</h5>
                <h5 className="text-start mt-4 text-black fw-bold" >
                  3 Months: <span className="fw-lighter"> Ongoing</span>
                  </h5>
                  <div className="mt-5">
                <ul>
                  <li>
                    FDA-approved, YAP-1 inhibition strategies will be tested on three patients, with measurements taken using HairDAO's tricholabs at respective hair transplant clinics. 
                    </li>
                    <li>Combination therapies, dosage, and protocol improvements will be generated by HairDAO in collaboration with Dr. Barghouthi and Dr. Bloxham.
                    </li>
                    <li>Education and reach-out by HairDAO to additional doctors, to further gauge demand for YAP-1 inhibitors.

                    </li>
                  </ul> 
                    </div>
                <h5 className="text-start mt-4 text-black fw-bold" >
                  6 Months: <span className="fw-lighter"> Ongoing</span>
                  </h5>
                  <div className="mt-5">
                <ul>
                  <li>Further in vivo testing of optimized YAP-1 inhibition strategies with Dr. Barghouthi, Dr. Bloxham, and additional doctors.
                    </li>
                    <li>Selection of path to market, with optimized dosage and protocol selected within range.
                    </li>
                    </ul>
                    
                <h5 className="text-start mt-4 text-black fw-bold" >
                  12 Months: <span className="fw-lighter"> Ongoing</span>
                  </h5>
                  <div className="mt-5">
                <ul>
                  <li>
                Additional in vivo testing of optimized dosage and protocol.
                </li>
                  
                  </ul>
                    </div>
                    </div>
                  
                
                </div>
                <div className="col-lg-3 img_col col-12">
                  <a className="navbar-brand text-white " href="/">
                    <Image className="img-fluid" width="500" height="500" src="/Image.png" alt="Logo1" />
                  </a>
                <h3 className="text-center mt-5  fw-bold">
                    YAP-1 IP
                  </h3>
                  <div className="text_field ">
                  <h5 className=" mt-4 text-black fw-bold" >
                  Funding: <span className="fw-lighter">$30,504.00</span>
                  </h5>
                  <h5 className=" mt- text-black fw-bold" >
                    Initiated:<span className="fw-lighter">ongoing</span>
                  </h5>
                  <h5 className=" mt- text-black fw-bold" >
                    Ownership:<span className="fw-lighter">ongoing</span>
                  </h5>
                  <h5 className=" mt- text-black fw-bold" >
                  Patent Status:<span className="fw-lighter">Not Filed</span>
                  </h5>
                  </div>
                </div>
            </div>
            </div>
            </div>
    
          </main>
          </>
      )
  }





